import { Business, SearchResult } from "./types";

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "1",
    name: "Дастархан",
    category: "Казахская кухня",
    address: "ул. Сатпаева, 14",
    city: "Атырау",
    rating: 4.8,
    reviewCount: 342,
    distance: 380,
    priceLevel: 2,
    isOpen: true,
    openUntil: "23:00",
    tags: ["Казахская", "Доступно", "Семейное"],
    aiScore: 96,
    aiReason: "Лучший рейтинг в категории, открыт сейчас, отличное соотношение цена/качество",
  },
  {
    id: "2",
    name: "Kebab House",
    category: "Донер / Фастфуд",
    address: "пр. Азаттык, 7",
    city: "Атырау",
    rating: 4.5,
    reviewCount: 218,
    distance: 620,
    priceLevel: 1,
    isOpen: true,
    openUntil: "02:00",
    tags: ["Донер", "Дешево", "До 2 ночи"],
    aiScore: 91,
    aiReason: "Самый доступный донер рядом, работает допоздна",
  },
  {
    id: "3",
    name: "Mono Coffee",
    category: "Кофейня",
    address: "ул. Маяковского, 32",
    city: "Атырау",
    rating: 4.7,
    reviewCount: 156,
    distance: 910,
    priceLevel: 2,
    isOpen: true,
    openUntil: "22:00",
    tags: ["Specialty кофе", "Тихо", "Wifi"],
    aiScore: 88,
    aiReason: "Топ кофейня города по отзывам, есть зоны для работы",
  },
  {
    id: "4",
    name: "Barberia Almaty",
    category: "Барбершоп",
    address: "ул. Панфилова, 101",
    city: "Алматы",
    rating: 4.9,
    reviewCount: 587,
    distance: 450,
    priceLevel: 2,
    isOpen: true,
    openUntil: "21:00",
    tags: ["Топ-мастера", "Запись онлайн", "Мужской стиль"],
    aiScore: 98,
    aiReason: "Наивысший рейтинг среди барбершопов Алматы, открыт сейчас",
  },
  {
    id: "5",
    name: "Nura Bistro",
    category: "Бистро / Европейская",
    address: "пр. Достык, 5",
    city: "Астана",
    rating: 4.6,
    reviewCount: 203,
    distance: 720,
    priceLevel: 3,
    isOpen: false,
    openUntil: "10:00",
    tags: ["Европейская", "Бизнес-ланч", "Вид на реку"],
    aiScore: 82,
    aiReason: "Отличные отзывы, но сейчас закрыто — откроется в 10:00",
  },
  {
    id: "6",
    name: "Самса у Нурлана",
    category: "Выпечка / Казахская",
    address: "ул. Бейбитшилик, 44",
    city: "Астана",
    rating: 4.4,
    reviewCount: 94,
    distance: 290,
    priceLevel: 1,
    isOpen: true,
    openUntil: "20:00",
    tags: ["Самса", "Дёшево", "Очередь стоит"],
    aiScore: 85,
    aiReason: "Народное место, самые дешевые самсы, высокий спрос",
  },
];

export const MOCK_SEARCH_RESULT: SearchResult = {
  query: "самый дешевый донер в городе",
  city: "Атырау",
  aiSummary:
    "Нашёл **3 места** с донерами в Атырау. Самый выгодный вариант — **Kebab House** на пр. Азаттык: цена от 800 ₸, рейтинг 4.5, работает до 2 ночи. Для ценителей качества — *Дастархан* (чуть дороже, но рейтинг 4.8 и 342 отзыва).",
  businesses: MOCK_BUSINESSES.slice(0, 3),
  processingMs: 1240,
};
